language: perl
sudo: true

perl:
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

install:
    - wget https://bitbucket.org/acoustid/chromaprint/downloads/chromaprint-1.2.tar.gz
    - tar -xvzf chromaprint-1.2.tar.gz
    - cd chromaprint-1.2
    - sudo apt-get install libboost-dev libavcodec-dev libavformat-dev libgtest-dev
    - cmake . && make && sudo make install
    - cd ..
    - cpanm --notest Pod::Checker Test::MemoryGrowth Test::Fatal

script:
    - make test
